package appestadistico;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class mainApp extends javax.swing.JFrame {

    DefaultTableModel dtm;
    
    DefaultTableModel dtn;
    
    //Inicializan los datos de la tabla
    Object[] o = new Object[5];
    Object[] u = new Object[3];
    
    
    //Almacena los datos de la tabla
    Object[] fi =  new Object[50];
    
    Object[] Fi =  new Object[50];
    
    Object[] hi =  new Object[50];
    
    Object[] Hi =  new Object[50];
    
    Object[] mdatos = new Object[50];
    
    Object[] mfi = new Object[50];
    
    Object[] media = new Object[50];
    
    public mainApp() {
        initComponents();
        
        
        dtm = (DefaultTableModel) tdatos.getModel();
        
        dtn = (DefaultTableModel) tmedia.getModel();
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdatos = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdatos = new javax.swing.JTable();
        txttotal = new javax.swing.JTextField();
        btnFi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tmedia = new javax.swing.JTable();
        btnModa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMedia = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnMediana = new javax.swing.JButton();
        btnFi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtdatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdatosKeyTyped(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpsan\\Documents\\NetBeansProjects\\AppEstadistico\\src\\assets\\Datos.png")); // NOI18N
        btn1.setText("Agregar Datos");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        tdatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATOS", "Frecuencia Absoluta (fi)", "Frecuencia Acumulada (Fi)", "Frecuencia Relativa (hi) %", "Frecuencia Relativa Acumulada (Hi) %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tdatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdatos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tdatos.setOpaque(false);
        tdatos.setRowHeight(20);
        tdatos.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tdatos.setShowHorizontalLines(false);
        tdatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tdatos);

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnFi.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFi.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpsan\\Documents\\NetBeansProjects\\AppEstadistico\\src\\assets\\Calcular.png")); // NOI18N
        btnFi.setText("Calcular Frecuencias");
        btnFi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Total:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Media:");

        tmedia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tmedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "fi", "Datos x fi"
            }
        ));
        tmedia.setRowHeight(20);
        tmedia.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tmedia.setShowGrid(false);
        jScrollPane2.setViewportView(tmedia);

        btnModa.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpsan\\Documents\\NetBeansProjects\\AppEstadistico\\src\\assets\\Moda.png")); // NOI18N
        btnModa.setText("Calcular Moda");
        btnModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mediana:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("APLICATIVO PARA CALCULAR FRECUENCIAS, MEDIDAS DE TENDECIA CENTRAL Y DISPERSION");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Moda"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnMedia.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpsan\\Documents\\NetBeansProjects\\AppEstadistico\\src\\assets\\Media.png")); // NOI18N
        btnMedia.setText("Calcular Media");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mediana"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Moda:");

        btnMediana.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpsan\\Documents\\NetBeansProjects\\AppEstadistico\\src\\assets\\Mediana.png")); // NOI18N
        btnMediana.setText("Calcular Mediana");
        btnMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedianaActionPerformed(evt);
            }
        });

        btnFi1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFi1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpsan\\Documents\\NetBeansProjects\\AppEstadistico\\src\\assets\\Limpiar.png")); // NOI18N
        btnFi1.setText("Limpiar");
        btnFi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1)
                                .addGap(37, 37, 37)
                                .addComponent(btnFi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFi1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMediana))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnFi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(btnMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        if(txtdatos.getText().length()== 0){
            JOptionPane.showMessageDialog(null, "Ingrese algun dato");
        } 
        else {
            
        o[0] = txtdatos.getText();
        dtm.addRow(o);
        
        
        txtdatos.setText("");
        txtdatos.requestFocus();
        
        }
        
        
        //Sumatoria de datos en el txttotal
        int total = 0;
        
        for(int i=0; i<dtm.getRowCount();i++){
            total += Integer.parseInt(dtm.getValueAt(i,0).toString());
            
        }
        
        String totaln = String.valueOf(total);
        
        //txttotal.setText(totaln);
        
                
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtdatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatosKeyTyped
        
        //Validando el campo para que solo ingrese numeros al txtdatos
        int key = evt.getKeyChar();
                
        if(Character.isLetter(key)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "!Ingrese solo números!");
        }
        
        
        
    }//GEN-LAST:event_txtdatosKeyTyped

    private void btnFiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiActionPerformed
        
        //CALCULAMOS LA FRECUENCIA ABSOLUTA
        int numeros;
        int contador = 0;
        
        //Capturas los valores del Fi
        
        double valorhi = 0;
        double contador2 = 0;
        
        double numerosHI;
        double contador3 = 0;
        
        for(int i=0; i<dtm.getRowCount();i++){
            numeros = Integer.parseInt(dtm.getValueAt(i,1).toString());
            //Le paso al fi los valores para almacenarlos
            fi[i] = numeros;
                contador = numeros + contador;
                //Le paso el valor al Fi para luego hacer un SET
                Fi[i] = String.valueOf(contador);
                //Utilizamos directamente el jtable para pasarle los datos
                tdatos.setValueAt(Fi[i], i, 2);
                
        }
        
        System.out.println(contador);
                      
        for(int i=0; i<dtm.getRowCount();i++){
            //Pasamos los datos decimal para realizar las operaciones
            valorhi = Math.round(Double.parseDouble(fi[i].toString())/ contador * 100);            
            contador2 = valorhi + contador2;
            //Probamos los resultados
            //System.out.println(valorhi+"%");
            //Le paso los datos convertidos en String al tdatos
            hi[i] = String.valueOf(valorhi);
            tdatos.setValueAt(hi[i]+"%", i, 3);
        }
        
        System.out.println(contador2);
        
        
        
        for(int i=0;i<dtm.getRowCount();i++){
            numerosHI = Double.parseDouble(hi[i].toString());
            contador3 = numerosHI + contador3;
            
            Hi[i] = String.valueOf(contador3);
            tdatos.setValueAt(Hi[i]+"%", i, 4);
            
        }
        
        
                 
    }//GEN-LAST:event_btnFiActionPerformed

    private void btnModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModaActionPerformed
        // TODO add your handling code here:
        
        int tamaño = 4;
        
        int[] arreglo = new int[tamaño];
        
        arreglo[0] = 2;
        arreglo[1] = 3;
        arreglo[2] = 4;
        arreglo[3] = 1;
        
        Arrays.sort(arreglo);
        
        for(int n : arreglo){
            System.out.println(n);
            
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnModaActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        // TODO add your handling code here:
        
        //Inicializamos la tabla con el obj u
        for(int i=0; i<dtm.getRowCount(); i++){
            u[0] = dtm.getValueAt(i,0);
            dtn.addRow(u);
            
            int numerosfi;
            int numerosdatos;
            int numerosmedia;
            
            
            //Obtenemos los varoles en las 2 variables
            numerosdatos = Integer.parseInt(dtm.getValueAt(i, 0).toString());
            numerosfi = Integer.parseInt(dtm.getValueAt(i, 1).toString());
            mdatos[i] = numerosdatos; 
            //Pasamos los valores a la columna correspondiente
            mfi[i] = numerosfi;            
            tmedia.setValueAt(mfi[i],i,1);
            //Operacion
            numerosmedia = (numerosdatos * numerosfi);
                                 
            media[i] = numerosmedia;
            
            tmedia.setValueAt(media[i],i,2);           
        }
                
        //Sumatoria de la media
        int totalmedia = 0;
        
        for(int i=0; i<dtn.getRowCount(); i++){
                       
            totalmedia += Integer.parseInt(dtn.getValueAt(i, 2).toString());
            
        }
        
        String sumamedia = String.valueOf(totalmedia);         
        txttotal.setText(sumamedia);
        
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedianaActionPerformed

    private void btnFi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnFi;
    private javax.swing.JButton btnFi1;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnMediana;
    private javax.swing.JButton btnModa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tdatos;
    private javax.swing.JTable tmedia;
    private javax.swing.JTextField txtdatos;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
